export const MAX_CONVERSION_FILE_SIZE_MB = 100;
export const MAX_CONVERSION_FILE_SIZE_BYTES = MAX_CONVERSION_FILE_SIZE_MB * 1024 * 1024;
export const MAX_CONVERSION_FILE_SIZE_LABEL = `${MAX_CONVERSION_FILE_SIZE_MB} MB`;
export const MAX_CONVERSION_BATCH_FILES = 10;
